
# tap repositories and their packages

tap 'caskroom/cask'
cask 'alcatraz'
cask 'alfred'
cask 'android-studio'
cask 'atom'
cask 'bettertouchtool'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'franz'
cask 'genymotion'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'java'
cask 'kap'
cask 'keybase'
cask 'kindlegen'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'rstudio'
cask 'sequel-pro'
cask 'sketch-toolbox'
cask 'sketch'
cask 'skype'
cask 'sourcetree'
cask 'spotify'
cask 'sublime-text'
cask 'vagrant-manager'
cask 'vagrant'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'xquartz'

tap 'eugenmayer/dockersync'
brew 'eugenmayer/dockersync/unox'

tap 'homebrew/bundle'

tap 'homebrew/completions'

tap 'homebrew/core'
brew 'apm-bash-completion'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'readline'
brew 'bash'
brew 'bash-completion'
brew 'bash-git-prompt'
brew 'git'
brew 'carthage'
brew 'coreutils'
brew 'figlet'
brew 'gmp'
brew 'gcc'
brew 'jpeg'
brew 'gdbm'
brew 'gettext'
brew 'git-lfs'
brew 'gnu-tar'
brew 'graphviz'
brew 'grep'
brew 'hub'
brew 'jrnl'
brew 'libevent'
brew 'memcached'
brew 'libmemcached'
brew 'libpcap'
brew 'macvim'
brew 'makedepend'
brew 'markdown'
brew 'mas'
brew 'mhash'
brew 'mcrypt'
brew 'mergepbx'
brew 'ncurses'
brew 'nmap'
brew 'nvm'
brew 'peco'
brew 'phantomjs'
brew 'pow'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'sslscan'
brew 'swiftlint'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'unison'
brew 'unixodbc'
brew 'watch'
brew 'xz'
brew 'yarn'
brew 'zlib'
brew 'zsh'

tap 'homebrew/dupes'

tap 'homebrew/php'
brew 'homebrew/php/php55-mcrypt'

tap 'homebrew/science'
brew 'homebrew/science/opencv3'
brew 'homebrew/science/r'

tap 'marcqualie/nginx'
brew 'marcqualie/nginx/nginx-full', args: ['with-sub']

