
# tap repositories and their packages

tap 'caskroom/cask'
cask 'abstract'
cask 'alfred'
cask 'android-studio'
cask 'bettertouchtool'
cask 'discord'
cask 'docker'
cask 'dropbox'
cask 'gitter'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-japanese-ime'
cask 'google-photos-backup-and-sync'
cask 'iterm2'
cask 'java'
cask 'kap'
cask 'kitematic'
cask 'minikube'
cask 'mi'
cask 'origami-studio'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'sequel-pro'
cask 'sketch'
cask 'slack'
cask 'sourcetree'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'xquartz'

tap 'caskroom/fonts'
cask 'font-hack-nerd-font'
cask 'font-lato'

tap 'eugenmayer/dockersync'
brew 'eugenmayer/dockersync/unox'

tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'sanemat/font'

mas 'Xcode', id: 497799835

brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'readline'
brew 'rename'
brew 'bash'
brew 'direnv'
brew 'fish'
brew 'git'
brew 'gs'
brew 'carthage'
brew 'coreutils'
brew 'figlet'
brew 'gmp'
brew 'gcc'
brew 'jpeg'
brew 'gdbm'
brew 'gettext'
brew 'git-lfs'
brew 'gnu-tar'
brew 'graphviz'
brew 'grep'
brew 'hub'
brew 'jrnl'
brew 'jq'
brew 'kops'
brew 'kubectl'
brew 'kube-aws'
brew 'libevent'
brew 'libpcap'
brew 'nodenv'
brew 'macvim'
brew 'makedepend'
brew 'markdown'
brew 'mas'
brew 'mhash'
brew 'mcrypt'
brew 'mergepbx'
brew 'ncurses'
brew 'nkf'
brew 'nmap'
brew 'opencv'
brew 'peco'
brew 'pow'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'ricty', args: ['vim-powerline', 'powerline']
brew 'the_silver_searcher'
brew 'sslscan'
brew 'swiftlint'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'unison'
brew 'unixodbc'
brew 'vim', args: ['with-lua']
brew 'watch'
brew 'xz'
brew 'yarn'
brew 'zlib'

tap 'marcqualie/nginx'
brew 'marcqualie/nginx/nginx-full', args: ['with-sub']

mas '1Password', id: 443987910
mas 'FreeMemory', id: 460931672
mas 'LINE', id: 539883307
mas 'Pages', id: 409201541
mas 'Realm Browser', id: 1007457278
mas 'Shazam', id: 897118787
mas 'SoundCloud', id: 412754595
mas 'StuffIt Expander', id: 405580712
mas 'The Unarchiver', id: 425424353
mas 'WinArchiver Lite', id: 414855915
